pins/urls.py
from django.urls import path
from .views import (
        upload_pin, view_pin, 
        search_pin, edit_pin, 
        delete_pin, view_tag, 
        profile, bio_edit,
        toggle_like, liked_pins
    )

app_name = 'pins'

urlpatterns = [
    path('upload-pin/', upload_pin, name='upload_pin'),
    path('search-pin/', search_pin, name='search_pin'),
    path('bio-edit/', bio_edit, name='bio_edit'),
    path('liked-pins/', liked_pins, name='liked_pins'),
    path('view-pin/<int:pk>/', view_pin, name='view_pin'),
    path('edit-pin/<int:pk>/', edit_pin, name='edit_pin'),
    path('toggle-like/<int:pk>/', toggle_like, name='toggle_like'),
    path('delete-pin/<int:pk>/', delete_pin, name='delete_pin'),
    path('view-tag/<slug:slug>/', view_tag, name='view_tag'),
    path('profile/<str:username>', profile, name='profile'),
]

pinterest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.views import home, signup
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
                path('', home, name='home'),
                path('login/', LoginView.as_view(template_name='core/login.html'), name='login'),
                path('logout/', LogoutView.as_view(), name='logout'),
                path('signup/', signup, name='signup'),
                path('pins/', include('pins.urls')),
                path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user = models.ForeignKey(get_user_model(), related_name='profile', on_delete=models.CASCADE)
    bio = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.user.username
    
    def get_bio(self):
        if self.bio:
            return self.bio
        return 'No bio is set.'

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.core.paginator import Paginator
from django.contrib.auth import login
from pins.models import Pin


def home(request):
    template_name = 'core/home.html'
    pins_obj = Paginator(Pin.objects.all(), 12)
    pins = pins_obj.get_page(1)

    if request.htmx:
        template_name = 'core/parts/home_content.html'
        page = request.GET.get('page', None)
        if page:
            pins = pins_obj.get_page(page)
            template_name = 'core/parts/pins_grid_container.html'

    return render(request, template_name, {'pins': pins})


def signup(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')

    return render(request, 'core/signup.html', {'form': form})

core/templates/core/parts/home_content.html
<title>Pinterest</title>

<div class="grid">
    {% include 'core/parts/pins_grid_container.html' %}
</div>

core/templates/core/parts/navbar.html
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a
      class="navbar-item"
      hx-get="{% url 'home' %}"
      hx-swap="innerHTML transition:true"
      hx-target="#main"
      hx-push-url="{% url 'home' %}"
    >
      <h1 class="is-size-5 has-text-weight-semibold">Pinterest</h1>
    </a>

    <a role="button" class="navbar-burger">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div class="navbar-menu">
    <div class="navbar-start">
      <div class="navbar-item">
        <form
          hx-get="{% url 'pins:search_pin' %}"
          hx-push-url="true"
          hx-swap="innerHTML transition:true"
          hx-target="#main"
        >
          <div class="field has-addons">
            <div class="control">
              <input
                type="text"
                name="query"
                class="input"
                placeholder="Search..."
              />
            </div>
            <div class="control">
              <button class="button is-primary">
                <span class="icon">
                  <i class="fa-solid fa-magnifying-glass"></i>
                </span>
              </button>
            </div>
          </div>
        </form>
      </div>

      {% if request.user.is_authenticated %}
      <div class="navbar-item">
        <button title="Upload" class="button is-primary upload">
          <span class="icon">
            <i class="fa-solid fa-upload"></i>
          </span>
        </button>
      </div>
      <div class="navbar-item">
        <button
          hx-get="{% url 'pins:liked_pins' %}"
          hx-push-url="true"
          hx-swap="innerHTML transition:true"
          hx-target="#main"
          title="Likes"
          class="button is-warning"
        >
          <span class="icon">
            <i class="fa-solid fa-heart"></i>
          </span>
        </button>
      </div>
      {% endif %}
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          {% if request.user.is_authenticated %}
          <a
            hx-get="{% url 'pins:profile' request.user.username %}"
            hx-target="#main"
            hx-swap="innerHTML transition:true"
            hx-push-url="true"
            title="Profile"
            class="button is-primary"
          >
            <span class="icon">
              <i class="fa-solid fa-user"></i>
            </span>
          </a>
          <a href="{% url 'logout' %}" title="Logout" class="button is-danger">
            <span class="icon">
              <i class="fa-solid fa-right-from-bracket"></i>
            </span>
          </a>
          {% else %}
          <a href="{% url 'signup' %}" title="Signup" class="button is-primary">
            <span class="icon">
              <i class="fa-sharp fa-solid fa-user-plus"></i>
            </span>
          </a>
          <a href="{% url 'login' %}" title="Login" class="button is-light">
            <span class="icon">
              <i class="fa-solid fa-right-to-bracket"></i>
            </span>
          </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</nav>

core/templates/core/parts/pin_upload_response.html
<div id="imageUploadResponse">
  <span class="pt-1 pb-2 is-link" id="responseText"
    >Your image has been successfully upload.
    <a
      hx-get="{% url 'pins:view_pin' pin.pk %}"
      hx-swap="innerHTML transition:true"
      hx-push-url="{% url 'pins:view_pin' pin.pk %}"
      hx-target="#main"
      onclick="htmx.removeClass('#uploadPin', 'is-active')"
      >Click here</a
    >
    to see it.</span
  >
</div>

core/templates/core/parts/pins_grid_container.html
{% load static %} 

{% for pin in pins %} 
{% if forloop.last and pins.has_next %}
<figure
  hx-get="{{request.path}}?page={{pins.next_page_number}}{% if query %}&query={{query}}{% endif %}"
  hx-trigger="revealed"
  hx-swap="afterend transition:true 2s"
  hx-target="this"
  class="image grid-item"
>
{% else %}
  <figure class="image grid-item">
{% endif %}

    <a
      hx-get="{% url 'pins:view_pin' pin.pk %}"
      hx-swap="innerHTML transition:true"
      hx-push-url="{% url 'pins:view_pin' pin.pk %}"
      hx-target="#main"
    >
      <img src="{{pin.thumbnail.url}}" height="{{pin.thumbnail.height}}" width="{{pin.thumbnail.width}}"/>
    </a>
  </figure>
{% endfor %}
<script type="text/javascript" src="{% static 'layout.js' %}" defer></script>

core/templates/core/parts/upload_pin.html
<div class="modal px-5" id="uploadPin">
  <div class="modal-background" onclick="closeModal()"></div>
  <div class="modal-card">
    <form
      id="uploadForm"
      hx-post="{% url 'pins:upload_pin' %}"
      hx-target="#imageUploadResponse"
      hx-swap="outerHTML"
      hx-on::before-request="removeResponseText(), showProgressBar()"
      hx-on::after-request="removeProgressBar()"
      hx-on::send-abort:="removeProgressBar()"
      hx-sync="closest form:drop"
      enctype="multipart/form-data"
    >
      <header class="modal-card-head">
        <p class="modal-card-title">Upload</p>
        <button
          onclick="closeModal()"
          class="delete"
          aria-label="close"
        ></button>
      </header>
      <section class="modal-card-body">
        <div id="imageUploadResponse"></div>
        <progress
          class="progress is-link is-hidden mt-3"
          id="progress"
          value="0"
          max="100"
        ></progress>
        <div class="field">
          <label class="label">Image</label>
          <div class="control">
            <input
              class="input"
              type="file"
              accept="image/*"
              name="image"
              required
            />
            <p class="help">Upload an image</p>
          </div>
        </div>
        <div class="field">
          <label class="label">Tags</label>
          <div class="control">
            <input
              type="text"
              class="input"
              name="tags"
              maxlength="255"
              required
            />
            <p class="help">
              Write some tags that others can find it, separated by comma.
            </p>
          </div>
        </div>
      </section>
      <footer class="modal-card-foot">
        <button class="button is-success" id="imageUpload">Upload</button>
        <a
          id="abortUpload"
          onclick="htmx.trigger('#uploadForm', 'htmx:abort')"
          role="button"
          class="button is-hidden"
          >Cancel</a
        >
      </footer>
    </form>
  </div>
</div>