pins/urls.py
from django.urls import path
from .views import (
        upload_pin, view_pin, 
        search_pin, edit_pin, 
        delete_pin, view_tag, 
        profile, bio_edit,
        toggle_like, liked_pins
    )

app_name = 'pins'

urlpatterns = [
    path('upload-pin/', upload_pin, name='upload_pin'),
    path('search-pin/', search_pin, name='search_pin'),
    path('bio-edit/', bio_edit, name='bio_edit'),
    path('liked-pins/', liked_pins, name='liked_pins'),
    path('view-pin/<int:pk>/', view_pin, name='view_pin'),
    path('edit-pin/<int:pk>/', edit_pin, name='edit_pin'),
    path('toggle-like/<int:pk>/', toggle_like, name='toggle_like'),
    path('delete-pin/<int:pk>/', delete_pin, name='delete_pin'),
    path('view-tag/<slug:slug>/', view_tag, name='view_tag'),
    path('profile/<str:username>', profile, name='profile'),
]

pinterest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.views import home, signup
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
                path('', home, name='home'),
                path('login/', LoginView.as_view(template_name='core/login.html'), name='login'),
                path('logout/', LogoutView.as_view(), name='logout'),
                path('signup/', signup, name='signup'),
                path('pins/', include('pins.urls')),
                path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pins/models.py
from django.db import models
from django.contrib.auth import get_user_model
from taggit.managers import TaggableManager
from .utils import make_thumbnail


class Pin(models.Model):
    created_by = models.ForeignKey(get_user_model(), related_name='pins', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='pins', null=False, blank=False)
    thumbnail = models.ImageField(upload_to='pins/thumbnails', null=True, blank=True)
    tags = TaggableManager()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.created_by.username + ' - ' + str(self.created_at)
    
    def get_total_like(self):
        no_of_likes = Pin.objects.filter(id=self.id).annotate(number=models.Count('likes')).distinct()
        return no_of_likes[0].number    
    
    def save(self, *args, **kwargs):
        if self.image:
            self.thumbnail = make_thumbnail(self.image)

        return super(Pin, self).save(*args, **kwargs)
    

class Like(models.Model):
    pin = models.ForeignKey(Pin, related_name='likes', on_delete=models.CASCADE)
    like_by = models.ForeignKey(get_user_model(), related_name='likes', on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.pin} by {self.like_by.get_username}"

    
    
    

pins/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Pin, Like
from taggit.models import Tag
from core.models import Profile
from django.core.paginator import Paginator
from django.contrib.auth import get_user_model
from .decorators import verify_owner


@login_required
def upload_pin(request):
    if request.method == 'POST':
        image = request.FILES.get('image', None)
        tags = request.POST.get('tags', None)
        if image and tags:
            tags = [x for x in tags.replace(',', ' ').split(' ') if x != '']
            pin = Pin.objects.create(created_by=request.user, image=image)
            for tag in tags:
                pin.tags.add(Tag.objects.get_or_create(name=tag.strip())[0])
            pin.save()
        
            return render(request, 'core/parts/pin_upload_response.html', {'pin': pin})


@verify_owner
@login_required
def edit_pin(request, pk):
    pin = get_object_or_404(Pin, pk=pk)
    template_name = 'pins/edit_pin.html'
    
    if request.htmx:
        template_name = 'pins/parts/edit_pin_content.html'

    if request.method == 'POST':
        image = request.FILES.get('image', None)
        tags = request.POST['tags']
        if image and tags:
            pin.image = image

            pin.tags.clear()

            for tag in [x for x in tags.replace(',', ' ').split(' ') if x != '']:
                pin.tags.add(Tag.objects.get_or_create(name=tag.strip())[0])
            pin.save()
            template_name = 'pins/parts/view_pin_content.html'

    return render(request, template_name, {'pin': pin})


@verify_owner
@login_required
def delete_pin(request, pk):
    pin = get_object_or_404(Pin, pk=pk)
    pin.delete()

    if request.htmx:
        pins = Pin.objects.all()[:12]
        return render(request, 'core/parts/home_content.html', {'pins': pins})
    
    return redirect('home')


def view_pin(request, pk):
    pin = Pin.objects.prefetch_related('tags').get(pk=pk)
    template_name = 'pins/view_pin.html'
    if request.htmx:
        template_name = 'pins/parts/view_pin_content.html'

    return render(request, template_name, {'pin': pin})

def view_tag(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    template_name = 'pins/view_tag.html'
    pin_obj = Paginator(Pin.objects.filter(tags__slug=tag.slug).distinct(), 12)
    pins = pin_obj.get_page(1)
    if request.htmx:
        template_name = 'pins/parts/view_tag_content.html'
        page = request.GET.get('page', None)
        if page:
            pins = pin_obj.get_page(page)
            template_name = 'core/parts/pins_grid_container.html'

    return render(request, template_name, {'pins': pins, 'tag': tag})

def profile(request, username):
    template_name = 'pins/profile.html'
    user = get_user_model().objects.prefetch_related('pins').get(username=username)
    pins_obj = Paginator(user.pins.all(), 12)
    pins = pins_obj.get_page(1)
    
    if request.htmx:
        template_name = 'pins/parts/profile_content.html'
        page = request.GET.get('page', None)
        if page:
            pins = pins_obj.get_page(page)
            template_name = 'core/parts/pins_grid_container.html'

    return render(request, template_name, {'user': user, 'pins': pins})

@login_required
def bio_edit(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        profile.bio = request.POST.get('bio', None)
        profile.save()

        if request.htmx:
            return render(request, 'pins/parts/bio.html')

    return render(request, 'pins/parts/bio_edit.html', {'bio': profile.bio})


def search_pin(request):
    query = request.GET.get('query', '')
    pins = None
    template_name = 'pins/search.html'
    if query:
        search_terms = [x for x in query.replace(',', ' ').split(' ') if x != '']
        pins_obj = Paginator(Pin.objects.filter(tags__name__in=search_terms).distinct(), 12)
        pins = pins_obj.get_page(1)

    if request.htmx:
        template_name = 'pins/parts/search_content.html'
        page = request.GET.get('page', None)
        if page:
            pins = pins_obj.get_page(page)
            template_name = 'core/parts/pins_grid_container.html'

    return render(request, template_name, {'query': query, 'pins': pins})

@login_required
def toggle_like(request, pk):
    
    if request.method == 'POST':
        pin = get_object_or_404(Pin, pk=pk)
        instance, created = Like.objects.get_or_create(pin=pin, like_by=request.user)
        if not created:
            instance.delete()

        return render(request, 'pins/parts/like.html', {'pin': pin})
    
@login_required
def liked_pins(request):
    template_name = 'pins/liked_pins.html'
    pins_obj = Paginator(Pin.objects.filter(likes__like_by=request.user), 12)
    pins = pins_obj.get_page(1)

    if request.htmx:
        template_name = 'pins/parts/liked_pins_content.html'
        page = request.GET.get('page', None)
        if page:
            pins = pins_obj.get_page(page)
            template_name = 'core/parts/pins_grid_container.html'

    return render(request, template_name, {'pins': pins})
        
    
    

pins/templates/pins/parts/bio.html
<article>
  {{user.profile.first.get_bio}}
</article>

{% if request.user == user %}
<a
  hx-get="{% url 'pins:bio_edit' %}"
  hx-swap="innerHTML transition:true"
  hx-target="#bio"
  class="button is-warning m-1"
  title="Edit"
><i class="fa-solid fa-pen-to-square"></i>
</a>
{% endif %}

pins/templates/pins/parts/bio_edit.html
<form
  hx-post="{% url 'pins:bio_edit' %}"
  hx-swap="innerHTML transition:true"
  hx-target="#bio"
  class="my-4"
>
  {% csrf_token %}
  <div class="columns">
    <div class="column is-4 is-offset-4">
      <div class="field">
        <div class="control">
          <textarea
            maxlength="300"
            class="textarea"
            placeholder="Write a bio about yourself"
            name="bio"
          >{{bio}}</textarea>
        </div>
      </div>
      <div class="control">
        <button class="button is-warning is-pulled-right">
          <i class="fa-solid fa-check"></i>
        </button>
      </div>
    </div>
  </div>
</form>

pins/templates/pins/parts/edit_pin_content.html
<title>Pinterest | Edit Pin</title>

<div class="columns is-multiline">
    <div class="column is-8 is-offset-2">
        <figure class="media-left columns is-multiline is-mobile is-gapless">
            <img id="updatePreview" class="column is-2" src="{{pin.thumbnail.url}}">
        </figure>
        <form id="editForm" enctype='multipart/form-data'
              hx-post="{% url 'pins:edit_pin' pin.pk %}"
              hx-swap="innerHTML transition:true"
              hx-target="#main"
              hx-on::before-request="htmx.toggleClass(htmx.find('#updateBar'), 'is-hidden');"
              hx-sync="closest form:drop"
        >

            {% csrf_token %}
            <progress id="updateBar" class="progress is-link is-hidden"></progress>
            <input class="input" type="file" accept="image/*" name="image"
                   onchange="document.getElementById('updatePreview').src = window.URL.createObjectURL(this.files[0])"
            >
            <input class="input mt-1" name="tags" type="text"
                   value="{% for tag in pin.tags.all %}{{ tag }}, {% endfor %}" required>
            <button class="button is-success mt-2">Update</button>

        </form>
    </div>
</div>

<script>

    htmx.on('#editForm', 'htmx:xhr:progress', function(evt) {
    htmx.find('#updateBar').setAttribute('value', evt.detail.loaded/evt.detail.total * 100)
    });

</script>

pins/templates/pins/parts/like.html
{% load extras %}
{% if request.user.is_authenticated %}
<a
  hx-post="{% url 'pins:toggle_like' pin.pk %}"
  hx-swap="outerHTML transition:true"
  hx-target="this"
  class="{% is_liked pin.pk request.user %} 
{% else %}
  <a
  {% endif %}
  button is-danger"
  title="Like"
>
  <i class="fa-solid fa-heart">&nbsp;{{pin.get_total_like}}</i>
</a>

pins/templates/pins/parts/liked_pins_content.html
<title>Pinterest | Liked Pins</title>

<div class="mb-6 has-text-centered">
    <h4 class="is-size-4"><strong>Liked Pins</strong></h4>
</div>

<div class="grid">
    {% include 'core/parts/pins_grid_container.html' %}
</div>

pins/templates/pins/parts/profile_content.html
<title>Pinterest | {{user.username}}</title>

<div class="mb-6 has-text-centered">
  <h4 class="is-size-4"><strong>{{user.username}}</strong></h4>
  <div id="bio">
    {% include 'pins/parts/bio.html' %}
  </div>
</div>
<div class="grid">
  {% include 'core/parts/pins_grid_container.html' %}
</div>

pins/templates/pins/parts/search_content.html
<title>Pinterest | Search Pins</title>

<div class="mb-6">
    <h4 class="is-size-4 has-text-centered"><strong>{{query}}</strong></h4>
</div>
<div class="grid">
    {% include 'core/parts/pins_grid_container.html' %}
</div>

pins/templates/pins/parts/view_pin_content.html
<title>Pinterest | Pin Details</title>

<div class="columns is-multiline">
  <div class="column is-8 is-offset-2">
    <div class="is-flex is-justify-content-space-between">
      <div>
        {% include 'pins/parts/like.html' %}
      </div>
      <div>
        <a
          href="{{ pin.image.url }}"
          class="button is-link is-outlined"
          title="Download"
          download
        >
          <i class="fa-solid fa-download"></i>
        </a>
        {% if request.user == pin.created_by %}
        <a
          hx-get="{% url 'pins:edit_pin' pin.pk %}"
          hx-swap="innerHTML transition:true"
          hx-target="#main"
          hx-push-url="true"
          class="button is-info is-outlined"
          title="Edit"
        >
          <strong><i class="fa-solid fa-pen-to-square"></i></strong>
        </a>
        <a
          hx-get="{% url 'pins:delete_pin' pin.pk %}"
          hx-swap="innerHTML transition:true"
          hx-target="#main"
          hx-confirm="Are you sure you want to delete this pin?"
          class="button is-danger is-outlined"
          title="Delete"
        >
          <i class="fa-solid fa-trash"></i>
        </a>
      </div>
      {% endif %}
    </div>
  </div>
  <div class="column is-8 is-offset-2">
    <div class="is-flex is-flex-direction-column is-align-items-center">
      <figure class="image">
        <img class="viewImage" loading="lazy" src="{{ pin.image.url }}" />
        <p class="mt-2 has-text-centered has-text-weight-semibold">
          <a
            hx-get="{% url 'pins:profile' pin.created_by %}"
            hx-swap="innerHTML transition:true"
            hx-target="#main"
            class="tag is-dark is-medium mt-1"
            >{{pin.created_by}}</a
          >
        </p>
      </figure>
      <div class="mt-2">
        {% if pin.tags %} {% for tag in pin.tags.all %}
        <a
          hx-get="{% url 'pins:view_tag' tag.slug %}"
          hx-target="#main"
          hx-swap="innerHTML transition:true"
          hx-push-url="{% url 'pins:view_tag' tag.slug %}"
          class="tag is-primary is-medium is-light"
          >{{tag.name}}</a
        >
        {% endfor %} {% endif %}
      </div>
    </div>
  </div>
</div>

pins/templates/pins/parts/view_tag_content.html
<title>Pinterest | {{tag.name}}</title>

<div class="mb-6">
    <h4 class="is-size-4 has-text-centered"><strong>{{tag.name}}</strong></h4>
</div>
<div class="grid">
    {% include 'core/parts/pins_grid_container.html' %}
</div>